### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by Mregy1** [tillo13/ai_storyboard_video_generator#1]
Hi, I am trying to install the script by Cloning the repository first:

git clone https://github.com/tillo13/kumori-story-generator.git

I got this message :
"Cloning into 'kumori-story-generator'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/tillo13/kumori-story-generator.git/' not found"

I found the repository does not exist : https://github.com/tillo13/kumori-story-generator

Help appreciated

**Comment by tillo13** [comment]
Ah, good catch, and oddly timely.  I was going to rewrite this today actually, and add in the ability to use Flux as the image generator, or allow it to run by adding pre-created images into it, so it works out well!

This was a v2 rebuild of the original one I built over here that also should work: https://github.com/tillo13/kumori_cli_engine

But this new one had a few updates to add in screen zoom/voiceover creations.  To fix your exact issue, swap in this exact git repo name that we're in currently: https://github.com/tillo13/ai_storyboard_video_generator.git

I'll update the readme also --let me know if I can help get you up and running!  The results of the what it makes are over here if you want to take a look/get ideas: https://www.youtube.com/@kumoriai/shorts

**Comment by Mregy1** [comment]
Thanks for providing me with end results. It looks pretty nice I like it. However, It's not exactly what I am seeking right now. Thank you for your response.
